#! /usr/bin/env bash

echo "== delete stack for s3 bucket via CFN"
# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/delete-stack.html

STACK_NAME="cfn-s3-simple"

aws cloudformation delete-stack \
--stack-name $STACK_NAME
--region us-east-2